### ISSUE TITLE
Implement Margin of The Vote

### ISSUE THREAD

**Issue by sshevlyagin** [govtrack/govtrack.us-web#105]
I want to clarify what you mean by margin of the vote. You said the margin of the vote (absolute value of one side's votes minus the other). Is this different than the absolute value of all the ayes vs all the nos?

**Comment by JoshData** [comment]
That's what I meant, yes.

**Comment by joelcollinsdc** [comment]
@JoshData was this what you were mentioning today?

**Comment by JoshData** [comment]
Right! Also see #108.

**Comment by JoshData** [comment]
Oh wait, I've already done widest/narrowest margin. I guess I meant #106. Closing this one.
