### ISSUE TITLE
2015 Report Card text - member description overflows onto picture

### ISSUE THREAD

**Issue by johnmhenson** [govtrack/govtrack.us-web#111]
The member description for each member is overflowing onto the member's picture on (at least) the 2015 member report cards.

**Comment by JoshData** [comment]
Can you post a screenshot and let me know your browser+version? I don't see the problem. Thanks.

**Comment by johnmhenson** [comment]
I was having the issue at work. It is IE, but not sure on the version.  Will check and get back to you.

**Comment by johnmhenson** [comment]
Issue appears to be fixed.
