### ISSUE TITLE
iOS safari UI problems with ../congress/votes

### ISSUE THREAD

**Issue by strictlymomo** [govtrack/govtrack.us-web#116]
https://www.govtrack.us/congress/votes

The rollcall list returned by the search query seems to have a couple problems in iOS safari:

- hyperlinks inaccessible
- text nodes and elements unselectable by cursor

The rest of the page seems to function normally.  Might be some settings in the wrapping list container for the search results?

**Comment by JoshData** [comment]
Hey thanks. Try now?

(For reference it also appeared to be broken in desktop Chrome with a very small (xs) window width.)

**Comment by strictlymomo** [comment]
Working!  Thanks for the prompt attention.

Great work btw, I think what you're doing is a very important civil service.

**Comment by JoshData** [comment]
Thanks! If you see other issues, let me know!

**Comment by strictlymomo** [comment]
Will do!  Are you interested in having some more data viz features for govtrack?  I've been looking over the data models and was considering working on some carousel-like list UI of roll calls that could dynamically update the d3 model that could be viewed as something like a graph chart of reps who voted for it.
