### ISSUE TITLE
Question: How did you arrive at DK for Dakota Territory and OL for Orleans Territory?

### ISSUE THREAD

**Issue by jpmckinney** [govtrack/govtrack.us-web#117]
https://github.com/govtrack/govtrack.us-web/blob/07477d560521665f0ad3049422189f2b852b1b75/us.py#L15

The [historical evidence](https://github.com/opencivicdata/ocd-division-ids/issues/136) I can find is that the abbreviations were DT and OT, which is what I'm recommending for Open Civic Data Division IDs.

**Comment by JoshData** [comment]
Hey James. I don't have any particular recollection but it was probably from the keys in the drop-down at http://bioguide.congress.gov/biosearch/biosearch.asp.

Two-letter postal abbreviations were invented after the Dakota Territory ceased to exist, so I don't think there is much to look at for standardization here.

**Comment by JoshData** [comment]
https://github.com/unitedstates/congress-legislators/issues/382
