### ISSUE TITLE
Data issue: DeVos confirmation vote includes Pence but omits Cortez Masto votes

### ISSUE THREAD

**Issue by bjacobel** [govtrack/govtrack.us-web#123]
The API response for the Senate's vote today on Betsy DeVos's confirmation ([`https://www.govtrack.us/api/v2/vote_voter?vote=118997`](https://www.govtrack.us/api/v2/vote_voter?vote=118997)) returns 100 `objects`. I believe there should be 101 objects returned, as Mike Pence cast the tiebreaking vote on a 50-50 split.

Mike Pence's vote is correctly included in the returned objects, but Catherine Cortez Masto's vote is not.

**Comment by JoshData** [comment]
All API calls are paged at 100 results at a time.

**Comment by bjacobel** [comment]
That makes perfect sense, `?limit=101` returns all the votes. Thank you, sorry for jumping to conclusions!
