### ISSUE TITLE
Limitations of GovTrack for State Legislatures

### ISSUE THREAD

**Issue by johnnyman727** [govtrack/govtrack.us-web#126]
Hello! I love GovTrack and use it every day to track updates from Congress. It makes it all the more cringe-worthy to try to use my state's legislation tracking tools (California).

I'm curious about what's been discussed thus far about applying GovTrack's underlying tech to various state's legislation tools. I'm sure there are lots of limitations, not the least of which is developer time, but I'd love to hear a TL;DR of if/how this could happen. I bet you folks have thought about this much longer than I have.

I'm also happy to contribute to a state effort.

**Comment by JoshData** [comment]
Hello. Almost all of the logic in GovTrack is tightly coupled with how Congress works and the specific data available about Congress. There is very little in here that is generic/reusable.

For state-based work, head over to our colleagues working on https://openstates.org/. They're holding an event soon! https://www.eventbrite.com/e/open-states-code-sprint-registration-32159601233?ref=ebtnebregn

**Comment by johnnyman727** [comment]
This is exactly what I was looking for. Thanks @JoshData!
