### ISSUE TITLE
Update Haystack

### ISSUE THREAD

**Issue by wbt** [govtrack/govtrack.us-web#130]
The [current version of Haystack](https://github.com/JoshData/django-haystack/tree/81b25f0d7fd4221fe63310cf3540ffe5baa2ed83) being used in GovTrack was last updated a couple years ago.  Since then, Django has updated and broken some things.  For example, in line 7 of [django-haystack/haystack/utils/loading.py](https://github.com/JoshData/django-haystack/blob/81b25f0d7fd4221fe63310cf3540ffe5baa2ed83/haystack/utils/loading.py), there's an old import: 

`from django.utils.datastructures import SortedDict`

which was [removed in Django 1.9](https://code.djangoproject.com/wiki/SortedDict).  ​[Collections.OrderedDict](http://docs.python.org/3/library/collections.html#collections.OrderedDict), added in Python 2.7, should be used instead.  This was [updated](https://github.com/django-haystack/django-haystack/commit/4afb61308b2a5618733ee77b00eaf595f6e9e067) in the [current version of django-haystack](https://github.com/django-haystack/django-haystack/blob/master/haystack/utils/loading.py), but that update wasn't carried through. 

I suggest updating haystack and/or specifying versions in the GovTrack readme.md.

Thanks for your work!

**Comment by JoshData** [comment]
Thanks for pointing that out. We're stuck on an old version of Django anyway though.

**Comment by JoshData** [comment]
See  #139.
