### ISSUE TITLE
django-twilio losing support

### ISSUE THREAD

**Issue by wbt** [govtrack/govtrack.us-web#132]
FYI, the [django-twilio dependency](https://github.com/govtrack/govtrack.us-web/blob/master/build/pipreq.txt) is [only partially supported](https://github.com/rdegges/django-twilio/issues/94#issuecomment-273278893) and decreasingly compatible with other libraries as they update.  I haven't looked into how tight the dependency is, but it might be a good idea to eventually remove it OR plan to be making any needed changes in that code-base too.

**Comment by jheld** [comment]
I'll be cutting a release soon with updated code. So, if you'd consider re-enabling support for this dependency, that would be great. Let me know if there's anything I can do.
