### ISSUE TITLE
Extra lines in accessing people data

### ISSUE THREAD

**Issue by wbt** [govtrack/govtrack.us-web#145]
When accessing [https://www.govtrack.us/data/db/django-fixture-people.json](https://www.govtrack.us/data/db/django-fixture-people.json), there are an extra two debugging lines at the start which throw off a JSON parser:

`Activating .venv virtual environment.    `     
`Loading settings from local/settings.env.`

**Comment by JoshData** [comment]
Ooops. It was fixed by 7b1bfb90cec0ca36b20ab25add364a3da10983a2 but I had to re-generate the file, which I've done now.

**Comment by wbt** [comment]
Thanks!  

In case this recurs in the future and someone else is finding the issue, the workaround was to add this line after the `wget `in the [Vagrantfile](https://github.com/govtrack/govtrack.us-web/blob/master/Vagrantfile):

`tail -n 1 /tmp/django-fixture-people.json > /tmp/django-fixture-people-fixed.json`

and then change the file used in the next substantive line of code (shown as amended):
`./manage.py loaddata /tmp/django-fixture-people-fixed.json`

This will eliminate any amount of leading lines with debug information, and is robust to continue working with almost no ill effect (little bit of extra computation & temp storage) after leading debug lines are removed.  (Tailing debug lines could be handled with `head` instead of or in addition to `tail`.)
