### ISSUE TITLE
CSRF cookies not getting set right

### ISSUE THREAD

**Issue by wbt** [govtrack/govtrack.us-web#146]
After some recent update, CSRF cookies are not getting set properly in modern browsers, leading to HTTP 403 errors when e.g. clicking to enter an emoji reaction.  I observe the HTTP 403 and the lack of a csrftoken cookie when viewing the current live govtrack.us in Chrome 60.0.3112.113, Firefox 43.0.1, and Opera 47.0.2631.55.  Interestingly, the CSRF cookies were loaded when browsing with Firefox 37.0.1.   I am browsing over HTTPS.   

Other cookies, such as _ga, _gid, _gat, ad_exp, __qca, and flags are getting sent and saved, so this is not an issue of the browsers not accepting cookies.

**Comment by wbt** [comment]
I think this issue has something to do with the [twostream decorators](https://github.com/govtrack/govtrack.us-web/blob/master/twostream/decorators.py) preventing generation of CSRF tokens on anonymous views.   

A workaround is to visit a page such as "Your Docket" (`/accounts/docket`) to get a csrftoken cookie, then reload a bill page and repeat the action triggering an AJAX post request that tries to use it (e.g. bill reaction).

**Comment by JoshData** [comment]
Hang on. I'll look right now. It probably has to do with the Django upgrade a few weeks ago.

**Comment by wbt** [comment]
OK, thanks.  It's not especially urgent for me because I have the workaround, but it is failing functionality on the live site for some users.

**Comment by JoshData** [comment]
Should be fixed now in ba77faa9d9e2c609fa4c1587bf86a0e909ec2c0c. Lemme know if you still see the problem.

**Comment by wbt** [comment]
Looks like it works.  Thanks much!
