### ISSUE TITLE
reating a new account doesn't send confirm email

### ISSUE THREAD

**Issue by wamoyo** [govtrack/govtrack.us-web#149]
Tried email and Twitter auth... both failed. -Sad Citizen-

**Comment by JoshData** [comment]
Thanks! I'm looking into it. I just re-sent emails that were supposed to have gone out so you should have it, and I'll be looking into why they didn't go out the first time.

**Comment by JoshData** [comment]
I think this is fixed. If you see anything else not working, let me know!
