### ISSUE TITLE
Broken links for sponsorshipanalysis_s.txt and sponsorshipanalysis_h.txt 

### ISSUE THREAD

**Issue by dockiem** [govtrack/govtrack.us-web#156]
Can you please include these files in the repository?

https://www.govtrack.us/data/us/115/stats/sponsorshipanalysis_h.txt
https://www.govtrack.us/data/us/115/stats/sponsorshipanalysis_s.txt

Those links are broken

**Comment by JoshData** [comment]
The files have moved --- I migrated everything to a new server and moved things around. The links are updated at https://www.govtrack.us/about/analysis#ideology. Thanks.

**Comment by dockiem** [comment]
thank you!
