### ISSUE TITLE
suggestion: "Secret Sauce" -> "Prognosis" in search sort

### ISSUE THREAD

**Issue by zacanger** [govtrack/govtrack.us-web#320]
Suggestion: consider changing "secret sauce" to "prognosis", or adding that option, in bill sort. Right now "secret sauce" is confusing, since... are we sorting by thousand island dressing? Are we sorting by pixie dust and frog eyes? Who knows? But there's a column called "Prognosis" so a user might expect to find a "Prognosis" sort. It's also not clear what `proscore` actually is except that right now it's the best way to (roughly) sort by prognosis.

**Comment by JoshData** [comment]
Thanks for the comment. It's not sorting based on prognosis. It's a related statistical prediction that works better for search by down-scoring a pattern of bills that have high likelihood to be enacted but aren't interesting, including post office naming bills. I don't know what to call that in the sort selection box.

**Comment by zacanger** [comment]
👍 got it. I think adding prognosis to the sort options might be useful, but I'll trust you folks that this secret sauce sort is more valuable :)
